package org.domain.mybiblio.entity;


import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.Length;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "CATEGORY", catalog = "biblio")
public class Category implements java.io.Serializable {

	private Integer idCategory;
	private String nameCategory;
	private Set<CategoryBook> categoryBooks = new HashSet<CategoryBook>(0);

	public Category() {
	}

	public Category(String nameCategory, Set<CategoryBook> categoryBooks) {
		this.nameCategory = nameCategory;
		this.categoryBooks = categoryBooks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_CATEGORY", unique = true, nullable = false)
	public Integer getIdCategory() {
		return this.idCategory;
	}

	public void setIdCategory(Integer idCategory) {
		this.idCategory = idCategory;
	}

	@Column(name = "NAME_CATEGORY", length = 150)
	@Length(max = 150)
	public String getNameCategory() {
		return this.nameCategory;
	}

	public void setNameCategory(String nameCategory) {
		this.nameCategory = nameCategory;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<CategoryBook> getCategoryBooks() {
		return this.categoryBooks;
	}

	public void setCategoryBooks(Set<CategoryBook> categoryBooks) {
		this.categoryBooks = categoryBooks;
	}

}
