package org.domain.mybiblio.entity;


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * CategoryBook generated by hbm2java
 */
@Entity
@Table(name = "CATEGORY_BOOK", catalog = "biblio")
public class CategoryBook implements java.io.Serializable {

	private Integer idCategoryBook;
	private Book book;
	private Category category;

	public CategoryBook() {
	}

	public CategoryBook(Book book, Category category) {
		this.book = book;
		this.category = category;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_CATEGORY_BOOK", unique = true, nullable = false)
	public Integer getIdCategoryBook() {
		return this.idCategoryBook;
	}

	public void setIdCategoryBook(Integer idCategoryBook) {
		this.idCategoryBook = idCategoryBook;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_BOOK", nullable = false)
	@NotNull
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CATEGORY", nullable = false)
	@NotNull
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

}
